include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    prefer_const_constructors_in_immutables: error
    use_key_in_widget_constructors: error
    unnecessary_const: error
    unused_import: error
    sized_box_for_whitespace: error
    no_logic_in_create_state: error
    await_only_futures: error
    unnecessary_brace_in_string_interps: error
    constant_identifier_names: error
    #avoid_print: error

linter:
  rules:
    file_names: false
    unnecessary_this: false
    non_constant_identifier_names: false
    prefer_is_empty: false
    unnecessary_new: false
    avoid_function_literals_in_foreach_calls: false
    use_full_hex_values_for_flutter_colors: false
    prefer_collection_literals: false
    empty_catches: false
    use_build_context_synchronously: false
    sort_child_properties_last: false
    depend_on_referenced_packages: false
